### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ayushparikh-code**

### CODE REVIEW

**Comment by gvanrossum** [comment]
Sorry, I am not interested in unsolicited PRs.

**Comment by Ayushparikh-code** [comment]
> Sorry, I am not interested in unsolicited PRs.

Unsolicited means ?

**Comment by gvanrossum** [comment]
I don't know you and I didn't ask for updates to this README.

**Comment by Ayushparikh-code** [comment]
> I don't know you and I didn't ask for updates to this README.

Ok I understand no problem 👍

**Comment by Ayushparikh-code** [comment]
> I don't know you and I didn't ask for updates to this README.

It's my pleasure that I'm talking to you (creater of Python) .so you have my huge respect Sir ! 🙏

**Pull request closed without merging**
